# Generated by Django 4.2.28 on 2026-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
