# Generated by Django 4.2.28 on 2026-02-21 16:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_exercise_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="PulseMind v1", max_length=100),
                ),
                ("version", models.FloatField(default=1.0)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("total_training_samples", models.PositiveIntegerField(default=0)),
                ("weights_info", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("day_number", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["day_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="PlanExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets", models.PositiveIntegerField(default=3)),
                ("reps", models.CharField(default="8-12", max_length=50)),
                ("target_weight", models.FloatField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exercise"
                    ),
                ),
                (
                    "plan_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="core.planday",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planday",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="core.workoutplan",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="planned_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executed_sessions",
                to="core.planday",
            ),
        ),
    ]
